# configs/SONICS_predictions/sonics_pred_across_runs_vis.yaml

files:
  - "results/Predictions/FakeRealMusicOriginal/Sonics_predictions_SpecTTTra-α-120s/full_track/predictions.json"
  - "results/Predictions/FakeRealMusicOriginalNormalized/minus14/reverb_room/Sonics_predictions_SpecTTTra-α-120s/full_track/predictions.json"
  - "results/Predictions/FakeRealMusicOriginalNormalized/minus23/reverb_room/Sonics_predictions_SpecTTTra-α-120s/full_track/predictions.json"

models:
  - ElevenLabs
  - SUNO
  - SUNO_PRO
  - UDIO
  - REAL

threshold: 0.5
annotate: true

output:
  result_path: "results/Predictions/Runs_comparison"
