data:
  features_path: "results/SpectrogramExplainability/FakeRealMusicOriginal/Occlusion/STFT_Occlusion_1024_20pct_stride_10pct/occlusion_features/occlusion_patches"

output: 
  result_path: "results/SpectrogramExplainability/FakeRealMusicOriginal/Occlusion/STFT_Occlusion_1024_20pct_stride_10pct/occlusion_features/"