data:
  features_path: "results/FBP/FakeRealMusicOriginal/FBP_high_resolution_preset_rel_stft_att_0.25_mixture/fbp_features/fbp_bands"

output:
  result_path: "results/FBP/FakeRealMusicOriginal/FBP_high_resolution_preset_rel_stft_att_0.25_mixture/fbp_features/"