# configs/AudioLIME_configs/lime_features_vis.yaml

data:
  features_path: "results/AudioLIME/FakeRealMusicOriginal/AudioLIME_500_samples_full_track/lime_features/"

output:
  result_path: "results/AudioLIME/FakeRealMusicOriginal/AudioLIME_500_samples_full_track/lime_features/"

lime_comp_features:
  version: "reversed"