data:
  features_path: "results/AudioLIME/FakeRealMusicOriginalNormalized/minus23/reverb_room/AudioLIME_500_samples_full_track/lime_features/lime_components"

output:
  result_path: "results/AudioLIME/FakeRealMusicOriginalNormalized/minus23/reverb_room/AudioLIME_500_samples_full_track/lime_features/"